image: Visual Studio 2017

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

artifacts:
  - path: bin\Release\FirewatchFOVChanger.exe
    name: Firewatch FOV Changer

platform: Any CPU

configuration: Release

matrix:
  fast_finish: true

skip_commits:
  message: /^(?=.*update)(?=.*readme).*$/
  
pull_requests:
  do_not_increment_build_number: true

version: 1.0.{build}

deploy:
  release: FirewatchFOVChanger-v$(appveyor_build_version)
  description: 'Firewatch FOV Changer'
  provider: GitHub
  auth_token:
    secure: ltfXN53qT1hrXcMPfyqUoKjAKtYZ7eFyso5vsQRLLO5IFkn1+kgPueU0RfmGv/qc
  artifact: 'Firewatch FOV Changer'
  on:
    branch: master
    appveyor_repo_tag: true  
