using System.Reflection;
[assembly: AssemblyTitle("FirewatchFOVChanger")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("FirewatchFOVChanger")]
[assembly: AssemblyCopyright("Copyright © beatcracker 2017")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: AssemblyVersion("1.0.*")]
